### ISSUE TITLE
throttle and steering signals issue

### ISSUE THREAD

**Issue by FrankCAN** [StatueFungus/autonomous_driving#1]
Hi,
Very much appreciate for your code, it really helps me a lot.

But I am still looking for throttle and steering signals for rover controls.

I think "lanecontroller/throttle" is for speed control, if I am right.

But I cannot find steering control, is it "lanecontroller/steering"? But why no any publisher for this signal?

Many thanks for your help.

Best Regards
Frank

**Comment by StatueFungus** [comment]
Hi Frank,

You are right, "lanecontroller/throttle" is for speed control.

We use the pid package (http://wiki.ros.org/pid) to smooth the steering.
So we publish to the topic "state" and subscribe to "control_effort" of the pid controller.
The Lane-Tracking Node (lane_tracking_node.py) is responsible for publishing the "state" topic.
In the rovercontrol.launch we map the topic "lanecontroller/steering" to "control_effort".
Bot topics are subscribed by the rovercontrol/lanecontroller.cpp
Hope this was helpful.

Best Regards
Benedikt
